import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-svh max-w-md mx-auto my-12">
        <div
          className="w-full h-6 -mb-3 relative"
          style={{
            backgroundImage: "url('/media/parchment-top.png')",
            backgroundSize: "100% auto",
          }}
        />
        <div
          className="min-h-32 mx-2 px-6 py-6"
          style={{
            backgroundImage: "url('/media/parchment-body.gif')",
            backgroundSize: "100% 6rem",
            backgroundRepeat: "repeat-y",
          }}
        >
          {children}
        </div>
        <div
          className="w-full h-6 -mt-3 relative"
          style={{
            backgroundImage: "url('/media/parchment-bottom.png')",
            backgroundSize: "100% auto",
          }}
        />
      </body>
    </html>
  );
}
